### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Alex-the-666** [Alex-the-666/Rats#134]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  iceandfire (iceandfire-1.8.3.jar)
  ratscore (rats-3.2.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 11/17/19 10:47 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.network.play.server.SPacketSetPassengers.<init>(SourceFile:18)
	at its_meow.betteranimalsplus.common.entity.EntityLamprey.func_70071_h_(EntityLamprey.java:111)
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:2016)
	at net.minecraft.entity.EntityLivingBase.func_70098_U(EntityLivingBase.java:2489)
	at net.minecraft.world.World.func_72866_a(World.java:1988)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72866_a(World.java:2053)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.network.play.server.SPacketSetPassengers.<init>(SourceFile:18)
	at its_meow.betteranimalsplus.common.entity.EntityLamprey.func_70071_h_(EntityLamprey.java:111)
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:2016)
	at net.minecraft.entity.EntityLivingBase.func_70098_U(EntityLivingBase.java:2489)
	at net.minecraft.world.World.func_72866_a(World.java:1988)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72866_a(World.java:2053)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: fossil:fossil.nautilus (fossilsarcheology.server.entity.prehistoric.EntityNautilus)
	Entity ID: 201
	Entity Name: Nautilus
	Entity's Exact location: -877.88, 56.00, -644.56
	Entity's Block location: World: (-878,56,-645), Chunk: (at 2,3,11 in -55,-41; contains blocks -880,0,-656 to -865,255,-641), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
	Entity's Momentum: -0.08, 0.00, 0.14
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: test
	All players: 1 total; [EntityPlayerMP['PheasantKing15'/1332, l='test', x=-900.96, y=71.80, z=-664.34]]
	Chunk stats: ServerChunkCache: 1092 Drop: 0
	Level seed: 4781403482268177279
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-821,64,-700), Chunk: (at 11,4,4 in -52,-44; contains blocks -832,0,-704 to -817,255,-689), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
	Level time: 5831 game time, 5831 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 72480 (now: false), thunder time: 119241 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2513692848 bytes (2397 MB) / 4194304000 bytes (4000 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                                | Signature                                |
	|:------ |:----------------- |:------------ |:------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2       | minecraft.jar                         | None                                     |
	| LCHIJA | mcp               | 9.42         | minecraft.jar                         | None                                     |
	| LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | jei               | 4.15.0.268   | jei_1.12.2-4.15.0.268.jar             | None                                     |
	| LCHIJA | appleskin         | 1.0.9        | AppleSkin-mc1.12-1.0.9.jar            | None                                     |
	| LCHIJA | betteranimals     | 5.2.1        | betteranimals-5.2.1.jar               | None                                     |
	| LCHIJA | betteranimalsplus | 7.1.1        | betteranimalsplus-1.12.2-7.1.1.43.jar | None                                     |
	| LCHIJA | llibrary          | 1.7.19       | llibrary-1.7.19-1.12.2.jar            | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | fossil            | 8.0.3        | fossilsarcheology-8.0.3.jar           | None                                     |
	| LCHIJA | waila             | 1.8.26       | Hwyla-1.8.26-B41_1.12.2.jar           | None                                     |
	| LCHIJA | iceandfire        | 1.8.3        | iceandfire-1.8.3.jar                  | None                                     |
	| LCHIJA | rats              | 3.2.2        | rats-3.2.2.jar                        | None                                     |
	| LCHIJA | jade              | 0.1.0        | Jade-0.1.0.jar                        | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
iceandfire (iceandfire-1.8.3.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
ratscore (rats-3.2.2.jar)
  com.github.alexthe666.rats.server.misc.RatsRuntimePatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['PheasantKing15'/1332, l='test', x=-900.96, y=71.80, z=-664.34]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Alex-the-666** [comment]
> at its_meow.betteranimalsplus.common.entity.EntityLamprey.func_70071_h_(EntityLamprey.java:111)

other mod issue
