### ISSUE TITLE
Caused a ticking Tile Entity error when trying to Hopper Milk Buckets into the auto cheeser

### ISSUE THREAD

**Issue by KiakahaEvans** [Alex-the-666/Rats#206]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 24/03/20 22:36
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 2
	at com.github.alexthe666.rats.server.entity.tile.TileEntityAutoCurdler.getCapability(TileEntityAutoCurdler.java:354) ~[?:4.0.2] {re:classloading}
	at net.minecraftforge.items.VanillaInventoryCodeHooks.getItemHandler(VanillaInventoryCodeHooks.java:262) ~[?:?] {re:classloading}
	at net.minecraftforge.items.VanillaInventoryCodeHooks.getItemHandler(VanillaInventoryCodeHooks.java:220) ~[?:?] {re:classloading}
	at net.minecraftforge.items.VanillaInventoryCodeHooks.insertHook(VanillaInventoryCodeHooks.java:121) ~[?:?] {re:classloading}
	at net.minecraft.tileentity.HopperTileEntity.func_145883_k(HopperTileEntity.java:150) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.tileentity.HopperTileEntity.func_200109_a(HopperTileEntity.java:105) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.tileentity.HopperTileEntity.func_73660_a(HopperTileEntity.java:92) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World.func_217391_K(World.java:621) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.rats.server.entity.tile.TileEntityAutoCurdler.getCapability(TileEntityAutoCurdler.java:354)
	at net.minecraftforge.items.VanillaInventoryCodeHooks.getItemHandler(VanillaInventoryCodeHooks.java:262)
	at net.minecraftforge.items.VanillaInventoryCodeHooks.getItemHandler(VanillaInventoryCodeHooks.java:220)
	at net.minecraftforge.items.VanillaInventoryCodeHooks.insertHook(VanillaInventoryCodeHooks.java:121)
	at net.minecraft.tileentity.HopperTileEntity.func_145883_k(HopperTileEntity.java:150)
	at net.minecraft.tileentity.HopperTileEntity.func_200109_a(HopperTileEntity.java:105)
	at net.minecraft.tileentity.HopperTileEntity.func_73660_a(HopperTileEntity.java:92)

-- Block entity being ticked --
Details:
	Name: minecraft:hopper // net.minecraft.tileentity.HopperTileEntity
	Block: Block{minecraft:hopper}[enabled=true,facing=north]
	Block location: World: (78,70,-351), Chunk: (at 14,4,1 in 4,-22; contains blocks 64,0,-352 to 79,255,-337), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Block: Block{minecraft:hopper}[enabled=true,facing=north]
	Block location: World: (78,70,-351), Chunk: (at 14,4,1 in 4,-22; contains blocks 64,0,-352 to 79,255,-337), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:621)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Kiakaha'/17528, l='Create', x=79.89, y=70.50, z=-351.13]]
	Chunk stats: ServerChunkCache: 2728
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Create
	Level seed: 1151999383975801616
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (53,64,16), Chunk: (at 5,4,0 in 3,1; contains blocks 48,0,16 to 63,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 470340 game time, 482654 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 176331 (now: false), thunder time: 124586 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2083990824 bytes (1987 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.3
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.3-client.jar Minecraft {minecraft@1.14.4 DONE}
		inventorysorter-1.14.4-16.2.0.jar Simple Inventory Sorter {inventorysorter@16.2.0 DONE}
		theoneprobe-1.14-1.4.37.jar The One Probe {theoneprobe@NONE DONE}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 DONE}
		MouseTweaks-2.13-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		BiomesOPlenty-1.14.4-9.0.0.262-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.259 DONE}
		platforms-1.14-1.5.1.jar Platforms {platforms@1.5.0 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		Druidcraft-1.14-0.3.1.jar Druidcraft {druidcraft@0.3.1 DONE}
		invtweaks-1.14.4-1.0.2.jar Inventory Tweaks Reborn {invtweaks@1.14.4-1.0.2 DONE}
		curios-FORGE-1.14.4-1.0.6.1.jar Curios API {curios@FORGE-1.14.4-1.0.6.1 DONE}
		Botania r1.11-378.jar Botania {botania@r1.11-378 DONE}
		Patchouli-1.14.4-1.1-26.jar Patchouli {patchouli@1.14.4-1.1-25 DONE}
		Neat 1.5-19.jar Neat {neat@1.5-19 DONE}
		Mantle-1.14.4-1.4.32.jar Mantle {mantle@1.4.32 DONE}
		create-mc1.14.4_v0.2.jar Create {create@0.2 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		gravestone-1.15.3.jar Gravestone Mod {gravestone@1.15.3 DONE}
		RandomThings-MC1.14.4-5.0.1.jar Random Things {randomthings@5.0.1 DONE}
		journeymap-1.14.4-5.7.0b1.jar Journeymap {journeymap@1.14.4-5.7.0b1 DONE}
		FastWorkbench-1.14.4-2.1.4.jar FastWorkbench {fastbench@2.1.4 DONE}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 DONE}
		citadel-1.0.4-1.14.4.jar Citadel {citadel@1.0.4 DONE}
		rats-4.0.2-1.14.4.jar Rats {rats@4.0.2 DONE}
		OreExcavation-1.6.147.jar Ore Excavation {oreexcavation@NONE DONE}
		SereneSeasons-1.14.4-2.0.0.40-universal.jar Serene Seasons {sereneseasons@1.14.4-2.0.0.40 DONE}
		engineerstools-1.14.4-1.0.6.jar Engineer's Tools {engineerstools@1.0.6 DONE}
		randompatches-1.14.4-1.21.0.0.jar RandomPatches {randompatches@1.14.4-1.21.0.0 DONE}
		NaturesAura-20.3.jar Nature's Aura {naturesaura@version DONE}
		FastFurnace-1.14.4-2.2.4.jar FastFurnace {fastfurnace@2.2.4 DONE}
		engineersdecor-1.14.4-1.0.20-b1.jar Engineer's Decor {engineersdecor@1.0.20-b1 DONE}
		clearwater-1.3.jar Clear Water {clearwater@1.3 DONE}
		tramplestopper-1.14.4-2.0.0.26-universal.jar Trample Stopper {tramplestopper@1.14.4-2.0.0.26-universal DONE}
		TMechworks-1.14.4-2.0.1.jar Tinkers' Mechworks {tmechworks@2.0.1 DONE}
		instantunify-1.14.4-1.0.3.jar InstantUnify {instantunify@1.0.3 DONE}
		forge-1.14.4-28.2.3-universal.jar Forge {forge@28.2.3 DONE}
		Quark-r2.0-212.jar Quark {quark@r2.0-212 DONE}
		shetiphiancore-1.14-3.6.1.jar ShetiPhian-Core {shetiphiancore@3.6.1 DONE}
		CleanView-1.15.2-v1.jar CleanView {cleanview@1.15.2-v1 DONE}
		PrettyBeaches_1.14.4-3.0.7.jar Pretty Beaches {prettybeaches@3.0.7 DONE}
		StevesFactoryManager-1.14.4-3.0.0-alpha26.jar Steve's Factory Manager {sfm@1.14.4-3.0.0-alpha DONE}
		CraftingTweaks_1.14.4-10.2.1.jar Crafting Tweaks {craftingtweaks@10.2.1 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['Kiakaha'/17528, l='Create', x=79.89, y=70.50, z=-351.13]]
	Data Packs: vanilla, mod:arl, mod:biomesoplenty, mod:botania, mod:citadel, mod:cleanview, mod:clearwater, mod:craftingtweaks, mod:create, mod:curios, mod:druidcraft, mod:engineersdecor, mod:engineerstools, mod:fastbench, mod:fastfurnace, mod:forge, mod:gravestone, mod:instantunify, mod:inventorysorter, mod:invtweaks, mod:jei, mod:journeymap, mod:mantle, mod:mousetweaks, mod:naturesaura, mod:neat, mod:oreexcavation, mod:patchouli, mod:placebo, mod:platforms, mod:prettybeaches, mod:quark, mod:randompatches, mod:randomthings, mod:rats, mod:sereneseasons, mod:sfm, mod:shetiphiancore, mod:swingthroughgrass, mod:theoneprobe, mod:tmechworks, mod:tramplestopper
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by KiakahaEvans** [comment]
Nice work bro
Awesome mod. love it
