### ISSUE TITLE
Crash when using wormhole potions, 1.12.2

### ISSUE THREAD

**Issue by OTRD5k** [Alex-the-666/Rats#281]
Someone used a potion, every client crashed, and the server also crashed.

Log from server end:

```
[05:01:21] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.ClassCastException: com.bloodnbonesgaming.triumph.events.InventoryUpdateListener cannot be cast to net.minecraft.entity.player.EntityPlayerMP
        at cursedflames.bountifulbaubles.wormhole.ContainerWormhole.detectAndSendChanges(ContainerWormhole.java:121) ~[ContainerWormhole.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.onUpdate(EntityPlayerMP.java:324) ~[oq.class:?]
        at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996) ~[amu.class:?]
        at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) ~[oo.class:?]
        at net.minecraft.world.World.updateEntity(World.java:1958) ~[amu.class:?]
        at net.minecraft.world.WorldServer.tickPlayers(WorldServer.java:642) ~[oo.class:?]
        at net.minecraft.world.World.updateEntities(World.java:1737) ~[amu.class:?]
        at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more
```

**Comment by OTRD5k** [comment]
I am the big dumb and put this in the wrong repo. Sorry
