### ISSUE TITLE
Server crashing when people join the Ratlantis dimension

### ISSUE THREAD

**Issue by Naxanria** [Alex-the-666/Rats#294]
See https://github.com/FTBTeam/FTB-Omnia/issues/87

**Comment by Alex-the-666** [comment]
Caused by: java.lang.NullPointerException
	at be.nevoka.betterbedrockgenerator.utils.Utils.getDimId(Utils.java:18) ~[?:0.0.6] {re:classloading}
	at be.nevoka.betterbedrockgenerator.BetterBedrockGenerator.shouldModifyBedrock(BetterBedrockGenerator.java:34) ~[?:0.0.6] {re:mixin,re:classloading}
	at net.minecraft.world.gen.NoiseChunkGenerator.handler$zze000$makeBedrock(NoiseChunkGenerator.java:532) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:assets/betterbedrockgenerator/betterbedrockgenerator.mixins.json:MixinFlattenBedrock,pl:mixin:A}


not a rats issue.
