### ISSUE TITLE
[1.12.2]Entity rat throwing exception during loading

### ISSUE THREAD

**Issue by p1ut0nium-git** [Alex-the-666/Rats#295]
Rats 3.2.11
Forge 14.23.5.2847

I keep getting this in my server's log:

`An Entity rats:rat(Rat) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
net.minecraft.util.ReportedException: Loading entity NBT
	at net.minecraft.entity.Entity.readFromNBT(Entity.java:1878) ~[vg.class:?]
	at net.minecraft.entity.EntityList.createEntityFromNBT(EntityList.java:221) [vi.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.createEntityFromNBT(AnvilChunkLoader.java:602) [aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.readChunkEntity(AnvilChunkLoader.java:529) [aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486) [aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:89) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:135) [on.class:?]
	at net.minecraft.world.World.getChunk(World.java:310) [amu.class:?]
	at net.minecraft.world.ChunkCache.<init>(ChunkCache.java:37) [and.class:?]
	at net.minecraft.pathfinding.PathNavigate.getPathToPos(SourceFile:113) [ze.class:?]
	at net.minecraft.pathfinding.PathNavigateGround.getPathToPos(SourceFile:65) [zd.class:?]
	at net.minecraft.pathfinding.PathNavigate.getPathToXYZ(SourceFile:93) [ze.class:?]
	at net.minecraft.pathfinding.PathNavigate.tryMoveToXYZ(SourceFile:143) [ze.class:?]
	at net.minecraft.entity.ai.EntityAIWander.startExecuting(SourceFile:65) [yc.class:?]
	at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:102) [xf.class:?]
	at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:763) [vq.class:?]
	at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359) [vp.class:?]
	at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:577) [vq.class:?]
	at net.minecraft.entity.monster.EntityMob.onLivingUpdate(EntityMob.java:45) [ade.class:?]
	at net.minecraft.entity.monster.AbstractSkeleton.onLivingUpdate(AbstractSkeleton.java:144) [acp.class:?]
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179) [vp.class:?]
	at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:295) [vq.class:?]
	at net.minecraft.entity.monster.EntityMob.onUpdate(EntityMob.java:50) [ade.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996) [amu.class:?]
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) [oo.class:?]
	at net.minecraft.world.World.updateEntity(World.java:1958) [amu.class:?]
	at net.minecraft.world.World.redirect$updateEntity$zbd000(World.java:4123) [amu.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1762) [amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) [oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: 
	at java.util.UUID.fromString(Unknown Source) ~[?:1.8.0_221]
	at com.github.alexthe666.rats.server.entity.EntityRat.readEntityFromNBT(EntityRat.java:638) ~[EntityRat.class:?]
	at net.minecraft.entity.Entity.readFromNBT(Entity.java:1866) ~[vg.class:?]
	... 36 more`

**Comment by BenjaminLeSire** [comment]
See #287
