### ISSUE TITLE
Crash on world load when running alongside obfuscate

### ISSUE THREAD

**Issue by Virtualistik** [Alex-the-666/Rats#322]
`---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 6/17/20 12:20 PM
Description: Ticking memory connection

java.lang.RuntimeException: Provider com.github.alexthe666.citadel.server.CitadelServerEvents$1.getCapability() returned null; return LazyOptional.empty() instead!
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:107) ~[?:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:118) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.getCapability(LivingEntity.java:2978) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.getCapability(PlayerEntity.java:2199) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at com.mrcrayfish.obfuscate.common.data.SyncedPlayerData.getDataHolder(SyncedPlayerData.java:166) ~[?:0.4.3-1.15.2] {re:classloading,pl:capability_inject_definalize:A}
	at com.mrcrayfish.obfuscate.common.data.SyncedPlayerData.onPlayerJoinWorld(SyncedPlayerData.java:204) ~[?:0.4.3-1.15.2] {re:classloading,pl:capability_inject_definalize:A}
	at net.minecraftforge.eventbus.ASMEventHandler_59_SyncedPlayerData_onPlayerJoinWorld_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraft.world.server.ServerWorld.func_217448_f(ServerWorld.java:871) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217435_c(ServerWorld.java:863) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:167) ~[?:?] {re:classloading}
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:116) ~[?:?] {re:classloading}
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:63) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:224) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:107)
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:118)
	at net.minecraft.entity.LivingEntity.getCapability(LivingEntity.java:2978)
	at net.minecraft.entity.player.PlayerEntity.getCapability(PlayerEntity.java:2199)
	at com.mrcrayfish.obfuscate.common.data.SyncedPlayerData.getDataHolder(SyncedPlayerData.java:166)
	at com.mrcrayfish.obfuscate.common.data.SyncedPlayerData.onPlayerJoinWorld(SyncedPlayerData.java:204)
	at net.minecraftforge.eventbus.ASMEventHandler_59_SyncedPlayerData_onPlayerJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraft.world.server.ServerWorld.func_217448_f(ServerWorld.java:871)
	at net.minecraft.world.server.ServerWorld.func_217435_c(ServerWorld.java:863)
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:167)
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:116)
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:224)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@30a19e2f
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 923462160 bytes (880 MB) / 1567096832 bytes (1494 MB) up to 2863661056 bytes (2731 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3072m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.20.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.20.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.20.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.20.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.20.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.20
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.20-client.jar Minecraft {minecraft@1.15.2 DONE}
		obfuscate-0.4.3-1.15.2.jar Obfuscate {obfuscate@0.4.3 DONE}
		forge-1.15.2-31.2.20-universal.jar Forge {forge@31.2.20 DONE}
		citadel-1.1.10.jar Citadel {citadel@1.1.10 DONE}
		rats-5.3.1-1.15.2.jar Rats {rats@5.3.1 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['Snorpy'/266, l='New World', x=-46.50, y=79.00, z=178.50]]
	Data Packs: vanilla, mod:obfuscate (incompatible), mod:forge (incompatible), mod:citadel (incompatible), mod:rats (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'`

**Comment by Virtualistik** [comment]
turns out it was just citadel and nothing to do with rats! also duplicate issue https://github.com/Alex-the-666/Citadel/issues/9

**Comment by Virtualistik** [comment]
Turns out it was specifically Citadel and had nothing to do with rats, reverting to 1.1.7 fixed it.
