### ISSUE TITLE
[1.12.2] Crash during startup

### ISSUE THREAD

**Issue by CrashPlayer** [Alex-the-666/Rats#327]
Minecraft simply doesn't start because of the mod.
OS: kali-rolling-amd64 (installed deb minecraft launcher package)
Logs:

15:22:07.238
Preparing to launch minecraft client for 1.12.2-forge-14.23.5.2854

15:22:08.020
Checking installations.

15:22:08.021
Minecraft client 1.12.2-forge-14.23.5.2854 is ready to start.

15:22:08.021
Starting!

15:22:08.032
Version does not support log configuration, will assume one plaintext entry per line

15:22:08.045
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true

15:22:09.459
[15:22:09] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker

15:22:09.476
[15:22:09] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker

15:22:09.477
[15:22:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker

15:22:09.505
[15:22:09] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading

15:22:09.506
[15:22:09] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_212, running on Linux:amd64:5.6.0-kali2-amd64, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre

15:22:09.698
[15:22:09] [main/INFO] [FML]: Searching /home/######/.minecraft/mods for mods

15:22:09.699
[15:22:09] [main/INFO] [FML]: Searching /home/######/.minecraft/mods/1.12.2 for mods

15:22:09.720
[15:22:09] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in rats-3.2.12-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.

15:22:09.733
[15:22:09] [main/WARN] [FML]: The coremod ratscore (com.github.alexthe666.rats.server.asm.RatsPlugin) is not signed!

15:22:09.735
[15:22:09] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker

15:22:09.737
[15:22:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker

15:22:09.740
[15:22:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker

15:22:09.741
[15:22:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper

15:22:12.688
[15:22:12] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557

15:22:12.802
[15:22:12] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc

15:22:12.805
[15:22:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper

15:22:12.807
[15:22:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker

15:22:13.469
[15:22:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper

15:22:13.474
Exception in thread "main" [15:22:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: com/github/alexthe666/rats/server/misc/RatsRuntimePatcher

15:22:13.475
[15:22:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.github.alexthe666.rats.server.asm.RatsPlugin.getASMTransformerClass(RatsPlugin.java:18)

15:22:13.475
[15:22:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:129)

15:22:13.476
[15:22:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)

15:22:13.476
[15:22:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

15:22:13.478
[15:22:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

15:22:13.478
[15:22:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

15:22:13.479
[15:22:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more

15:22:13.479
[15:22:13] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NoClassDefFoundError: net/ilexiconn/llibrary/server/asm/RuntimePatcher

15:22:13.480
[15:22:13] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass1(Native Method)

15:22:13.480
[15:22:13] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)

15:22:13.483
[15:22:13] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)

15:22:13.483
[15:22:13] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)

15:22:13.483
[15:22:13] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	... 6 more

15:22:13.483
[15:22:13] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.ClassNotFoundException: net.ilexiconn.llibrary.server.asm.RuntimePatcher

15:22:13.483
[15:22:13] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[15:22:13] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

15:22:13.483
[15:22:13] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

15:22:13.483
[15:22:13] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	... 10 more

15:22:13.556
Process crashed with exit code 1`

**Comment by Alex-the-666** [comment]
install LLibrary mod
