### ISSUE TITLE
1.16.1 | Game freezes after using the Golem Mount Upgrade

### ISSUE THREAD

**Issue by Orpheus05** [Alex-the-666/Rats#335]
java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.ai.attributes.AttributeModifierManager.func_233795_c_(SourceFile:62) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_233637_b_(LivingEntity.java:1728) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_110138_aP(LivingEntity.java:1508) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.<init>(LivingEntity.java:206) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.<init>(MobEntity.java:107) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at com.github.alexthe666.rats.server.entity.EntityRatMountBase.<init>(EntityRatMountBase.java:40) ~[?:6.0.1-1.16.1] {re:classloading}
	at com.github.alexthe666.rats.server.entity.EntityRatGolemMount.<init>(EntityRatGolemMount.java:33) ~[?:6.0.1-1.16.1] {re:classloading}
	at net.minecraft.entity.EntityType.func_200721_a(EntityType.java:439) ~[?:?] {re:classloading}
	at com.github.alexthe666.rats.server.entity.EntityRat.func_70636_d(EntityRat.java:1513) ~[?:6.0.1-1.16.1] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2157) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:299) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:604) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_217390_a(World.java:596) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:397) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:791) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:81) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251] {}

**Comment by Akulav** [comment]
Same +
