### ISSUE TITLE
Placing Rat cages do crash client and server on 1.16

### ISSUE THREAD

**Issue by InflamedSebi** [Alex-the-666/Rats#343]
Placing Rat cages do crash client and server:
Tested Forge Version 1.16.1-32.0.57 up to latest (.61)
<details>
  <summary>Crash log</summary>

```
   [m[1;31m[19:05:23] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
  java.lang.NoSuchMethodError: net.minecraft.block.BlockState.canBeConnectedTo(Lnet/minecraft/world/IBlockReader;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/Direction;)Z
    at com.github.alexthe666.rats.server.blocks.BlockRatCage.func_196258_a(BlockRatCage.java:112) ~[?:6.0.2-1.16.1] {re:classloading,pl:runtimedistcleaner:A}
    at net.minecraft.item.BlockItem.func_195945_b(BlockItem.java:105) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
    at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:51) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
    at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
    at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:596) ~[?:?] {re:classloading}
    at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:184) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
    at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:353) ~[?:?] {re:classloading}
    at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:895) ~[?:?] {re:classloading,xf:fml:backpacked:creative_inventory_action_fix,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
    at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
    at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
    at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
    at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
    at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
    at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
    at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:738) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:157) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
    at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:721) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:715) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B}
    at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:700) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:647) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252] {}
```
</details>

**Comment by Akulav** [comment]
Same for me

**Comment by Alex-the-666** [comment]
fixed
