### ISSUE TITLE
crashes with no error log

### ISSUE THREAD

**Issue by artzygal** [Alex-the-666/Rats#405]
possibly with ice and fire...which you made...

**Comment by artzygal** [comment]
this is the error from before
Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.10-1.12.2.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-48.jar)
  ratscore (rats-3.2.14-1.12.2.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 8/25/20 6:19 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Rats (rats)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id -8, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:134)
	at com.github.alexthe666.rats.server.world.RatsWorldRegistry.register(RatsWorldRegistry.java:17)
	at com.github.alexthe666.rats.RatsMod.init(RatsMod.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1417404768 bytes (1351 MB) / 3489660928 bytes (3328 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version        | Source                                        | Signature                                |
	|:----- |:------------------- |:-------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft           | 1.12.2         | minecraft.jar                                 | None                                     |
	| LCHI  | mcp                 | 9.42           | minecraft.jar                                 | None                                     |
	| LCHI  | FML                 | 8.0.99.99      | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHI  | forge               | 14.23.5.2847   | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHI  | advancedcombat      | 1.1.2          | advancedcombat-1.1.2-[1.12].jar               | None                                     |
	| LCHI  | aquaculture         | 1.6.8          | Aquaculture-1.12.2-1.6.8.jar                  | None                                     |
	| LCHI  | architecturecraft   | @VERSION@      | ArchitectureCraft-ElytraDev-Mod-1.12.2.jar    | None                                     |
	| LCHI  | baubles             | 1.5.2          | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHI  | atum                | 2.0.17         | Atum-1.12.2-2.0.17.jar                        | None                                     |
	| LCHI  | autoreglib          | 1.3-32         | AutoRegLib-1.3-32 (1).jar                     | None                                     |
	| LCHI  | bno                 | 1.12.2-1.0.4.0 | BasicNetherOres-1.12.2-1.0.4.0.jar            | None                                     |
	| LCHI  | biomesoplenty       | 7.0.1.2441     | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
	| LCHI  | llibrary            | 1.7.17         | llibrary-1.7.17-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHI  | fossil              | 8.0.4          | fossilsarcheology-8.0.4.jar                   | None                                     |
	| LCHI  | cfm                 | 6.3.1          | furniture-6.3.1-1.12.2.jar                    | None                                     |
	| LCHI  | gravestone          | 1.3.1          | GraveStone-1.12.2-Graves-1.3.1.jar            | None                                     |
	| LCHI  | gravestone-extended | 1.3.5.1        | GraveStone-1.12.2-Extended-1.3.5.1.jar        | None                                     |
	| LCHI  | iceandfire          | 1.9.1          | iceandfire-1.9.1-1.12.2.jar                   | None                                     |
	| LCHI  | jei                 | 4.15.0.291     | jei_1.12.2-4.15.0.291.jar                     | None                                     |
	| LCHI  | jeid                | 1.0.3-48       | JustEnoughIDs-1.0.3-48.jar                    | None                                     |
	| LCHI  | maidensmaterials    | 3.3            | Maiden's+Marvelous+Materials-3.3.jar          | None                                     |
	| LCHE  | rats                | 3.2.14         | rats-3.2.14-1.12.2.jar                        | None                                     |
	| LCH   | betteranimalsplus   | 9.0.1          | betteranimalsplus-1.12.2-9.0.1.jar            | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.10-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-48.jar)
  org.dimdev.jeid.JEIDTransformer
ratscore (rats-3.2.14-1.12.2.jar)
  com.github.alexthe666.rats.server.misc.RatsRuntimePatcher
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.5063' Renderer: 'Intel(R) HD Graphics 5500'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 20.19.15.5063
	OpenGlRenderer: Intel(R) HD Graphics 5500
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by artzygal** [comment]
i think i needed to download the new llibrary
