### ISSUE TITLE
Rats mod crashes on every first load of modpack export

### ISSUE THREAD

**Issue by aaronhowser1** [Alex-the-666/Rats#420]
https://pastebin.com/HvH00ag0

The interesting bit:
```java
[03:59:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: com/github/alexthe666/rats/server/misc/RatsRuntimePatcher
[03:59:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.github.alexthe666.rats.server.asm.RatsPlugin.getASMTransformerClass(RatsPlugin.java:18)
[03:59:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:129)
[03:59:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[03:59:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[03:59:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: com.github.alexthe666.rats.server.misc.RatsRuntimePatcher
[03:59:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[03:59:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[03:59:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[03:59:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[03:59:10] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NoClassDefFoundError: net/ilexiconn/llibrary/server/asm/RuntimePatcher
[03:59:10] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[03:59:10] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[03:59:10] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[03:59:10] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[03:59:10] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 6 more
[03:59:10] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.ClassNotFoundException: net.ilexiconn.llibrary.server.asm.RuntimePatcher
[03:59:10] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[03:59:10] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[03:59:10] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[03:59:10] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	... 10 more

```

Weirdly enough, it only ever crashes on the first launch. Every version after works fine.
This is using MC 1.12, `rats-3.2.14-1.12.2`

![image](https://user-images.githubusercontent.com/15698722/93315317-85e72e00-f7d0-11ea-8ef3-c1e546d8f26f.png)

**Comment by ShadowThunder992** [comment]
[crash-2022-02-06_03.47.34-client.txt](https://github.com/Alex-the-666/Rats/files/8009308/crash-2022-02-06_03.47.34-client.txt)
I don't know what's the problem ... :(

**Comment by GizmoTheMoonPig** [comment]
class no longer exists in modern versions, shouldnt be an issue there
