### ISSUE TITLE
[1.16.3] Crash when setting Rats to harvest-mode

### ISSUE THREAD

**Issue by KoriFox** [Alex-the-666/Rats#424]
===========
rats-6.1.0-1.16.3
===========

The game client completely freezes and stays that way until manually closed (alt+f4 or the cross button) at which it will state that it is no longer reacting and can be forced to exit.

This happens when setting rats to harvest-mode. Just opening their menu and selecting said option by clicking said button causes the freeze/crash.

Used mods:
- rats-6.1.0-1.16.3.jar
- citadel-1.4.0.jar

Forge environment:
- forge-1.16.3-34.0.13

Tested in singleplayer.

=====================================

Error log once this occured:

[24Sep2020 18:30:33.185] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:80) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:637) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$5467/1636579453.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.IllegalArgumentException: Missing required parameters: [<parameter minecraft:origin>]
	at net.minecraft.loot.LootContext$Builder.func_216022_a(LootContext.java:197) ~[?:?]
	at net.minecraft.block.AbstractBlock.func_220076_a(AbstractBlock.java:211) ~[?:?]
	at com.github.alexthe666.rats.server.entity.ai.RatAIHarvestCrops.resetTarget(RatAIHarvestCrops.java:57) ~[?:6.1.0-1.16.3]
	at com.github.alexthe666.rats.server.entity.ai.RatAIHarvestCrops.func_75250_a(RatAIHarvestCrops.java:45) ~[?:6.1.0-1.16.3]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75250_a(SourceFile:22) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector$$Lambda$5803/402905113.test(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51]
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:77) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?]
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?]
	at com.github.alexthe666.rats.server.entity.EntityRat.func_70636_d(EntityRat.java:950) ~[?:6.1.0-1.16.3]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606) ~[?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$5790/1719523622.accept(Unknown Source) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?]
	... 6 more

The exact crash report is attached.

[crash-2020-09-24_18.30.33-server.txt](https://github.com/Alex-the-666/Rats/files/5277724/crash-2020-09-24_18.30.33-server.txt)

**Comment by Largosaki** [comment]
This problem has been reproduced

Caused by: java.lang.IllegalArgumentException: Missing required parameters: [<parameter minecraft:origin>]
        at net.minecraft.loot.LootContext$Builder.func_216022_a(LootContext.java:197) ~[?:?] {re:classloading}
        at net.minecraft.block.AbstractBlock.func_220076_a(AbstractBlock.java:211) ~[?:?] {re:classloading,re:mixin}
        at com.github.alexthe666.rats.server.entity.ai.RatAIRaidCrops.func_75246_d(RatAIRaidCrops.java:64) ~[?:6.1.0-1.16.3] {re:classloading}
        at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading}
        at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(GoalSelector.java:136) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorGoalSelector,pl:mixin:A}
        at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMobEntity,pl:mixin:A}

**Comment by GizmoTheMoonPig** [comment]
fixed already, see above commit
