### ISSUE TITLE
World saving issues

### ISSUE THREAD

**Issue by As-12** [Alex-the-666/Rats#471]
The mod causes chunk saving issues with no specific error message. This appears only to happen in some random chunk far away from world spawn. 

I repeatedly getting these Chunk saving errors in my log file. Reloading the chunk causes all progress to be lost.

Forge:  34.1.25 (MC 16.3)

Mod installed: 
citadel-1.5.2
ratlantis-1.0.0-1.16.3
rats-7.0.1-1.16.3

[25Nov2020 11:45:54.148] [Server thread/ERROR] [net.minecraft.world.server.ChunkManager/]: Failed to save chunk 43,-3
java.lang.NullPointerException: null
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222649_a(ChunkSerializer.java:421) ~[?:?]
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222645_a(ChunkSerializer.java:363) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219229_a(ChunkManager.java:682) [?:?]
	at net.minecraft.world.server.ChunkManager.lambda$save$9(ChunkManager.java:351) [?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$6192/1942431882.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) [?:1.8.0_51]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) [?:1.8.0_51]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) [?:1.8.0_51]
	at net.minecraft.world.server.ChunkManager.func_219177_a(ChunkManager.java:348) [?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217210_a(SourceFile:321) [?:?]
	at net.minecraft.world.server.ServerWorld.func_217445_a(ServerWorld.java:693) [?:?]
	at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:528) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:75) [?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$5480/1452065221.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by GizmoTheMoonPig** [comment]
all issues regarding ratlantis are being closed as the dimension has been completely rewritten from the ground up and shouldnt have these issues anymore in 1.19 and beyond
