### ISSUE TITLE
1.16.4 Server Crash on Mining Rat

### ISSUE THREAD

**Issue by Rusettsten** [Alex-the-666/Rats#478]
According to one of the users on my server, the crash occured the first time he setup a mining rat. It had just found its first vein of Coal. Our modlist is at [https://docs.google.com/document/d/1arP_wf0jSKfr1FVbiELvPmGhTDL9KOsqrPJ9B4IDjEQ/edit?usp=sharing](https://docs.google.com/document/d/1arP_wf0jSKfr1FVbiELvPmGhTDL9KOsqrPJ9B4IDjEQ/edit?usp=sharing)

The full stack trace is:

[01Dec2020 00:09:03.236] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID c94b19b5-5e2f-4a08-88a3-b99eaf3ab65d
[01Dec2020 00:09:03.247] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Missing required parameters: [<parameter minecraft:origin>]
	at net.minecraft.loot.LootContext$Builder.func_216022_a(LootContext.java:197) ~[?:?]
	at net.minecraft.block.AbstractBlock.func_220076_a(AbstractBlock.java:211) ~[?:?]
	at com.github.alexthe666.rats.server.entity.RatUtils.destroyBlock(RatUtils.java:637) ~[rats:7.0.1-1.16.3]
	at com.github.alexthe666.rats.server.entity.RatUtils.doRatMinerLogic(RatUtils.java:623) ~[rats:7.0.1-1.16.3]
	at com.github.alexthe666.rats.server.entity.ai.RatAIDepositInInventory.func_75246_d(RatAIDepositInInventory.java:99) ~[rats:7.0.1-1.16.3]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:88) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?]
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?]
	at com.github.alexthe666.rats.server.entity.EntityRat.func_70636_d(EntityRat.java:978) ~[rats:7.0.1-1.16.3]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?]
	... 5 more

**Comment by Rusettsten** [comment]
Opening the project in Eclipse (and updating the forge dependencies to get it to run) reveals that the missing argument on the LootContainer Builder is "parameter minecraft:origin". Working on a fix now.

**Comment by Rusettsten** [comment]
See Pull Request #481
