### ISSUE TITLE
Rats bad speed

### ISSUE THREAD

**Issue by joklbash** [Alex-the-666/Rats#510]
After updating to your latest version, 7.0.2, I've started to see the server log files filled with the below error. It does not crash the server - just logs this error every second or two and causes the log to grow by GB. Running forge 35.1.3. Things were working ok with 7.0.1.

[Server thread/ERROR] [com.github.alexthe666.rats.RatsMod/]: Tried to set a bad speed:2.6 for entity:EntityRat['Rat'/23855, l='ServerLevel[world1]', x=26.75, y=67.00, z=-885.50]
java.lang.Exception: null
	at com.github.alexthe666.rats.server.pathfinding.RatAdvancedPathNavigate.func_75489_a(RatAdvancedPathNavigate.java:253) ~[rats:7.0.2-1.16.3]
	at com.github.alexthe666.rats.server.entity.ai.RatAIFleeMobs.func_75246_d(RatAIFleeMobs.java:117) ~[rats:7.0.2-1.16.3]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_271]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_271]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_271]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_271]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_271]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_271]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_271]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_271]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_271]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:88) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?]
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?]
	at com.github.alexthe666.rats.server.entity.EntityRat.func_70636_d(EntityRat.java:986) ~[rats:7.0.2-1.16.3]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**Comment by joklbash** [comment]
Sorry, got a 404 and double posted.
