### ISSUE TITLE
Rats 7.0.4 crash on server startup

### ISSUE THREAD

**Issue by BlueDuckYT** [Alex-the-666/Rats#527]
The mod is crashing on startup with apparently classes missing?  It has worked before, so it may just be a compatibility issue with another mod.

[12.01 10:36:38] [Server] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:upstream.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
[12.01 10:36:38] [Server] 	... more
[12.01 10:36:38] [Server] Caused byjava.lang.ClassNotFoundException: com.github.alexthe666.rats.server.entity.ai.RatAIHarvestQuarry$BlockSorter
[12.01 10:36:38] [Server] 	at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_{}
[12.01 10:36:38] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_{}
[12.01 10:36:38] [Server] 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.6.jar:?] {re:classloading}
[12.01 10:36:38] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_{}
[12.01 10:36:38] [Server] 	at com.github.alexthe666.rats.server.entity.ai.RatAIHarvestQuarry.<init>(RatAIHarvestQuarry.java:52) ~[rats:7.0.4-1.16.{re:classloading}
[12.01 10:36:38] [Server] 	at com.github.alexthe666.rats.server.entity.EntityRat.setupDynamicAI(EntityRat.java:355) ~[rats:7.0.4-1.16.{re:classloading,pl:runtimedistcleaner:A}
[12.01 10:36:38] [Server] 	at com.github.alexthe666.rats.server.entity.EntityRat.onUpgradeChanged(EntityRat.java:2910) ~[rats:7.0.4-1.16.{re:classloading,pl:runtimedistcleaner:A}
[12.01 10:36:38] [Server] 	at com.github.alexthe666.rats.server.entity.EntityRat.func_70636_d(EntityRat.java:984) ~[rats:7.0.4-1.16.{re:classloading,pl:runtimedistcleaner:A}
[12.01 10:36:38] [Server] 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:eidolon.mixins.json:LivingEntityMixin,pl:mixin:APP:neapolitan.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[12.01 10:36:38] [Server] 	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:buzzier_bees.mixins.json:MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[12.01 10:36:38] [Server] 	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[12.01 10:36:38] [Server] 	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
[12.01 10:36:38] [Server] 	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[12.01 10:36:38] [Server] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:upstream.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
[12.01 10:36:38] [Server] 	... more
[12.01 10:36:38] [Server] 	Suppressedjava.lang.ClassNotFoundException: Failed to find class bytes for com.github.alexthe666.rats.server.entity.ai.RatAIHarvestQuarry$BlockSorter
[12.01 10:36:38] [Server] 		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:260) ~[modlauncher-8.0.6.jar:?] {}
[12.01 10:36:38] [Server] 		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.6.jar:?] {re:classloading}
[12.01 10:36:38] [Server] 		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.6.jar:?] {re:classloading}
[12.01 10:36:38] [Server] 		at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_{}
[12.01 10:36:38] [Server] 		at com.github.alexthe666.rats.server.entity.ai.RatAIHarvestQuarry.<init>(RatAIHarvestQuarry.java:52) ~[rats:7.0.4-1.16.{re:classloading}
[12.01 10:36:38] [Server] 		at com.github.alexthe666.rats.server.entity.EntityRat.setupDynamicAI(EntityRat.java:355) ~[rats:7.0.4-1.16.{re:classloading,pl:runtimedistcleaner:A}
[12.01 10:36:38] [Server] 		at com.github.alexthe666.rats.server.entity.EntityRat.onUpgradeChanged(EntityRat.java:2910) ~[rats:7.0.4-1.16.{re:classloading,pl:runtimedistcleaner:A}
[12.01 10:36:38] [Server] 		at com.github.alexthe666.rats.server.entity.EntityRat.func_70636_d(EntityRat.java:984) ~[rats:7.0.4-1.16.{re:classloading,pl:runtimedistcleaner:A}
[12.01 10:36:38] [Server] 		at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:

**Comment by GizmoTheMoonPig** [comment]
NoSuchMethodError and ClassDefNotFound errors are something I havent been able to reproduce. These methods should exist, especially when it comes to AI tasks, so theres definitely something else going on here. Closing as this is something I cant exactly deal with without more context
