### ISSUE TITLE
Server Error when trying  to go into the Ratlantis Portal

### ISSUE THREAD

**Issue by HuskyInABasket** [Alex-the-666/Rats#575]
Hello! I am have a modded minecraft server with the Rats mod and everytime I try to enter the portal to go to Ratlantis The server console spews out this error:
**[00:55:56] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
net.minecraft.crash.ReportedException: Colliding entity with block**
at net.minecraft.entity.Entity.func_213315_a(Entity.java:577) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:generic-update-hook,xf:fml:quark:override-collision,xf:fml:immersiveengineering:IE wire damage,pl:runtimedistcleaner:A}
at net.minecraft.network.play.ServerPlayNetHandler.func_147347_a(ServerPlayNetHandler.java:730) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.network.play.client.CPlayerPacket.func_148833_a(SourceFile:126) ~[?:?] {re:classloading}
at net.minecraft.network.play.client.CPlayerPacket$PositionPacket.func_148833_a(SourceFile:57) ~[?:?] {re:classloading}
at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:classloading}
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:701) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:695) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:680) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:628) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}
**Caused by: java.lang.NullPointerException: Dimension type must not be null**
at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[server-1.14.4-extra-stable.jar:?] {}
at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:179) ~[?:?] {re:classloading}
at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:981) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at com.github.alexthe666.rats.server.blocks.BlockRatlantisPortal.func_196262_a(BlockRatlantisPortal.java:54) ~[?:4.1.1] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.block.BlockState.func_196950_a(BlockState.java:262) ~[?:?] {re:classloading,xf:fml:forgeendertech:randomTickBlock,pl:runtimedistcleaner:A}
at net.minecraft.entity.Entity.func_145775_I(Entity.java:838) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:generic-update-hook,xf:fml:quark:override-collision,xf:fml:immersiveengineering:IE wire damage,pl:runtimedistcleaner:A}
at net.minecraft.entity.Entity.func_213315_a(Entity.java:572) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:generic-update-hook,xf:fml:quark:override-collision,xf:fml:immersiveengineering:IE wire damage,pl:runtimedistcleaner:A}
... 14 more

**Comment by GizmoTheMoonPig** [comment]
all issues regarding ratlantis are being closed as the dimension has been completely rewritten from the ground up and shouldnt have these issues anymore in 1.19 and beyond
