### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Leogomo** [Alex-the-666/Rats#645]
I just installed the Ratlantis extension for my minecraft 1.16.5 (I already had the base ratmod and it worked fine), it works until the moment I try to load an already created world or create a new one, hence, as soon as the world begins, the game crash.
This is the full crash report 

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 08/03/21 10:22 AM
Description: Rendering screen

java.nio.channels.OverlappingFileLockException: null
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255) ~[?:1.8.0_202] {}
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152) ~[?:1.8.0_202] {}
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1107) ~[?:1.8.0_202] {}
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155) ~[?:1.8.0_202] {}
	at net.minecraft.server.SessionLockManager.func_232998_a_(SourceFile:42) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.SaveFormat$LevelSave.<init>(SaveFormat.java:277) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.world.storage.SaveFormat.func_237274_c_(SaveFormat.java:265) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1701) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$loadWorld$29(Minecraft.java:1804) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$deleteWorld$31(Minecraft.java:1839) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.ConfirmScreen.func_213002_b(SourceFile:41) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) ~[?:?] {re:classloading}
	at com.legacy.structure_gel.SGClientEvents.skipExperimentalBackupScreen(SGClientEvents.java:66) ~[structure_gel:1.7.5] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:297) ~[forge:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:729) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:821) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.0.44.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.0.44.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255) ~[?:1.8.0_202] {}
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152) ~[?:1.8.0_202] {}
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1107) ~[?:1.8.0_202] {}
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155) ~[?:1.8.0_202] {}
	at net.minecraft.server.SessionLockManager.func_232998_a_(SourceFile:42) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.SaveFormat$LevelSave.<init>(SaveFormat.java:277) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.world.storage.SaveFormat.func_237274_c_(SaveFormat.java:265) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1701) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$loadWorld$29(Minecraft.java:1804) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$deleteWorld$31(Minecraft.java:1839) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.ConfirmScreen.func_213002_b(SourceFile:41) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) ~[?:?] {re:classloading}
	at com.legacy.structure_gel.SGClientEvents.skipExperimentalBackupScreen(SGClientEvents.java:66) ~[structure_gel:1.7.5] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:297) ~[forge:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:729) ~[?:?] {re:classloading}
-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screen.WorldLoadProgressScreen
	Mouse location: Scaled: (426, 171). Absolute: (741.000000, 409.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:821) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.0.44.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.0.44.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.8.0-44-generic
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3483815376 bytes (3322 MB) / 5234491392 bytes (4992 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.0.44.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.44.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.0.44.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.44.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.0.44.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.44
	FML Language Providers: 
		javafml@36.0
		minecraft@1
		kotlinforforge@1.6.1
	Mod List: 
		forge-1.16.5-36.0.44-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		dwmh-1.16.4-0.4.0.2.jar                           |Dude! Where's my Horse?       |dwmh                          |1.16.4-0.4.0.2      |DONE      |NOSIGNATURE
		repurposed_structures-1.16.5-2.4.4.jar            |Repurposed Structures         |repurposed_structures         |1.16.5-2.4.4        |DONE      |NOSIGNATURE
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |DONE      |NOSIGNATURE
		Wyrmroost-1.16.3-1.2.11.jar                       |Wyrmroost                     |wyrmroost                     |1.16.3-1.2.11       |DONE      |NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |DONE      |NOSIGNATURE
		dungeons_plus-1.16.4-1.1.3.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.3               |DONE      |NOSIGNATURE
		CreativeCore_v2.1.0_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.71(1).jar                        |Just Enough Items             |jei                           |7.6.1.71            |DONE      |NOSIGNATURE
		abnormals_core-1.16.5-3.1.0.jar                   |Abnormals Core                |abnormals_core                |3.1.0               |DONE      |NOSIGNATURE
		astikorcarts-1.16.5-1.1.1.jar                     |AstikorCarts                  |astikorcarts                  |1.1.1               |DONE      |NOSIGNATURE
		upgrade_aquatic-1.16.5-3.0.1.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.0.1               |DONE      |NOSIGNATURE
		torohealth-1.16.4-forge-4.jar                     |ToroHealth                    |torohealth                    |NONE                |DONE      |NOSIGNATURE
		strawgolem-1.16-1.9.jar                           |Straw Golem                   |strawgolem                    |1.16-1.9            |DONE      |NOSIGNATURE
		extraboats-1.16.5-2.1.0.jar                       |Extra Boats                   |extraboats                    |2.1.0               |DONE      |NOSIGNATURE
		rediscovered-1.16.4-1.3.7.jar                     |Rediscovered                  |rediscovered                  |1.3.7               |DONE      |NOSIGNATURE
		citadel-1.6.2.jar                                 |Citadel                       |citadel                       |1.6.2               |DONE      |NOSIGNATURE
		rats-7.1.1-1.16.5.jar                             |Rats                          |rats                          |7.1.1               |DONE      |NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |DONE      |NOSIGNATURE
		moarboats-1.16.3-8.0.0.0-beta3.jar                |Moar Boats                    |moarboats                     |1.16.3-8.0.0.0-beta3|DONE      |NOSIGNATURE
		good-nights-sleep-1.16.4-1.2.13.jar               |Good Night's Sleep            |good_nights_sleep             |1.2.13              |DONE      |NOSIGNATURE
		WorldHandler-1.16.4-2.12.jar                      |World Handler                 |worldhandler                  |1.16.4-2.12         |DONE      |NOSIGNATURE
		ItemPhysic_v1.4.16_mc1.16.5.jar                   |ItemPhysic                    |itemphysic                    |1.6.0               |DONE      |NOSIGNATURE
		MinecraftEarthMod-2.0.1.3.jar                     |Minecraft Earth Mod           |minecraft_earth_mod           |2.0.1.3             |DONE      |NOSIGNATURE
		FallingTree-Forge-1.16.5-2.10.2.jar               |Falling Tree                  |fallingtree                   |2.10.2              |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.44-universal.jar                |Forge                         |forge                         |36.0.44             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		[1.16.X-1.0.10]+Dragon+Mounts+Legacy.jar          |Dragon Mounts: Legacy         |dragonmounts                  |1.0.10              |DONE      |NOSIGNATURE
		chiselsandbits-0.2.10-RELEASE.jar                 |Chisels & bits                |chiselsandbits                |NONE                |DONE      |NOSIGNATURE
		structure_gel-1.16.4-1.7.5(1).jar                 |Structure Gel API             |structure_gel                 |1.7.5               |DONE      |NOSIGNATURE
		ratlantis-1.0.0-1.16.3.jar                        |Rats: Ratlantis               |ratlantis                     |1.0.0-1.16.3        |DONE      |NOSIGNATURE
	Crash Report UUID: 969bab40-03d4-4597-9ad2-b82c94662c72
	Launched Version: 1.16.5-forge-36.0.44
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Mesa DRI Intel(R) HD Graphics 620 (KBL GT2) GL version 3.0 Mesa 20.0.8, Intel Open Source Technology Center
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210219-144623
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.0 Mesa 20.0.8
	OpenGlRenderer: Mesa DRI Intel(R) HD Graphics 620 (KBL GT2)
	OpenGlVendor: Intel Open Source Technology Center
	CpuCount: 4

**Comment by mtaudou** [comment]
It's doing the same to me, if i find the answer il will give it to you

**Comment by mtaudou** [comment]
Okay, I found the problem, if you are using dungeon + and structur gel API, it's them who cause the crash

**Comment by Gronglegrowth** [comment]
I am encountering this very same issue, though as it has been opened for a year at this point I'm not expecting a fix, but [here is my game log](https://mclo.gs/iSV4UTh). This happened on the modpack Unlikely Reunion (I updated its version of forge, and most of its mods, so this instance has the latest versions of just about everything).

**Comment by GizmoTheMoonPig** [comment]
Should be fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
