### ISSUE TITLE
Chicken rat mount ticking entity caused crash

### ISSUE THREAD

**Issue by Mbimajosh** [Alex-the-666/Rats#683]
Chicken rat mount ticking entity caused crash

**Comment by Mbimajosh** [comment]
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
Details:
	Entity Type: rats:rat_mount_chicken (com.github.alexthe666.rats.server.entity.EntityRatChickenMount)
	Entity ID: 53717
	Entity Name: Rat Chicken Mount
	Entity's Exact location: -1173.12, 67.00, -16.28
	Entity's Block location: World: (-1174,67,-17), Chunk: (at 10,4,15 in -74,-2; contains blocks -1184,0,-32 to -1169,255,-17), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: [EntityRat['Rat'/48, l='ServerLevel[world]', x=-1173.18, y=67.70, z=-16.36]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
	Entity NBT: {Brain:{memories:{}},HurtByTimestamp:0,ForgeData:{},Attributes:[{Base:16.0d,Modifiers:[{Amount:0.032116535473626834d,Operation:1,UUID:[I;-17498829,-734049034,-1558061537,-1730537795],Name:"Random spawn bonus"}],Name:"minecraft:generic.follow_range"},{Base:0.08d,Name:"forge:entity_gravity"},{Base:0.3d,Name:"minecraft:generic.movement_speed"}],Invulnerable:0b,FallFlying:0b,PortalCooldown:0,AbsorptionAmount:0.0f,FallDistance:0.0f,CanUpdate:1b,DeathTime:0s,BoundingBox:[-1173.4482610884345d,67.0d,-16.60240981862826d,-1172.7982611122764d,67.75d,-15.952409842470122d],ForgeCaps:{"mahoutsukai:mahou":{MAHOUTSUKAI_PLAYER_PREV_YAW:0.0f,MAHOUTSUKAI_SHOW_MAHOU:1b,MAHOUTSUKAI_MANA_FULL:1b,MAHOUTSUKAI_MANA_UP_COUNTER:100,MAHOUTSUKAI_PLAYER_POSSESSING:0b,MAHOUTSUKAI_AUTHORITY_HIT:0b,MAHOUTSUKAI_LAST_RECIPE_CLOTH:0b,MAHOUTSUKAI_PLAYER_HAS_MAGIC:0b,MAHOUTSUKAI_FAE_SPAWN:1b,MAHOUTSUKAI_PLAYER_CHARGE_RATE:0.1d,MAHOUTSUKAI_PLAYER_DAMAGE_EXCHANGE_USES:0,MAHOUTSUKAI_PLAYER_PREV_PITCH:0.0f,MAHOUTSUKAI_PLAYER_MAX_MANA:100,MAHOUTSUKAI_PLAYER_STORED_MANA:100,MAHOUTSUKAI_PLAYER_PROTECTIVE_DISPLACEMENT_USES:0,MAHOUTSUKAI_CANCEL_TIME:0L,MAHOUTSUKAI_PLAYER_DEATH_COLLECTION_USES_LEFT:0.0f},"mekanism:radiation":{radiation:1.0E-7d},"twilightforest:cap_shield":{permshields:0,tempshields:0},"citadel:extended_entity_data_citadel":{"Ice And Fire - Siren Property Tracker":{CharmedBySiren:0b,SirenID:0},"Ice And Fire - Frozen Property Tracker":{TicksUntilUnfrozen:0,IsFrozen:0b},"Ice and Fire - Player Property Tracker":{DismountedDragon:0b,GauntletDamage:0,DreadPortalZ:0,DreadPortalY:0,DreadPortalX:0},"Ice And Fire - Chain Property Tracker":{ConnectedEntities:[]}},"pneumaticcraft:hacking":{},"shrink:shrunk":{width:0.65f,isshrinking:0b,defaulteyeheight:0.69f,fixed:0b,isshrunk:0b,height:0.75f},"eidolon:knowledge":{signs:[],facts:[]}},HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,UUID:[I;-1785046181,-221821907,-1283431561,92160445],Motion:[0.0d,-0.0784000015258789d,0.0d],Health:4.0f,LeftHanded:0b,Air:300s,OnGround:1b,Rotation:[147.74664f,0.0f],HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],Passengers:[{Brain:{memories:{}},HurtByTimestamp:0,Owner:[I;-1859067292,530468527,-1904158419,83100662],Attributes:[{Base:128.0d,Modifiers:[{Amount:0.05294263143518061d,Operation:1,UUID:[I;-237157957,265635443,-1409152006,1007001525],Name:"Random spawn bonus"}],Name:"minecraft:generic.follow_range"},{Base:8.0d,Name:"minecraft:generic.max_health"},{Base:0.08d,Name:"forge:entity_gravity"},{Base:0.3d,Name:"minecraft:generic.movement_speed"},{Base:0.0d,Name:"minecraft:generic.armor"},{Base:1.0d,Name:"forge:swim_speed"},{Base:1.0d,Name:"minecraft:generic.attack_damage"}],Invulnerable:0b,AbsorptionAmount:0.0f,CheeseFeedings:10,RandomEffectCooldown:0,FallDistance:0.0f,Toga:0b,InLove:0,CanUpdate:1b,TransportingRF:0,ForgeCaps:{"mahoutsukai:mahou":{MAHOUTSUKAI_PLAYER_PREV_YAW:0.0f,MAHOUTSUKAI_SHOW_MAHOU:1b,MAHOUTSUKAI_MANA_FULL:1b,MAHOUTSUKAI_MANA_UP_COUNTER:100,MAHOUTSUKAI_PLAYER_POSSESSING:0b,MAHOUTSUKAI_AUTHORITY_HIT:0b,MAHOUTSUKAI_LAST_RECIPE_CLOTH:0b,MAHOUTSUKAI_PLAYER_HAS_MAGIC:0b,MAHOUTSUKAI_FAE_SPAWN:1b,MAHOUTSUKAI_PLAYER_CHARGE_RATE:0.1d,MAHOUTSUKAI_PLAYER_DAMAGE_EXCHANGE_USES:0,MAHOUTSUKAI_PLAYER_PREV_PITCH:0.0f,MAHOUTSUKAI_PLAYER_MAX_MANA:100,MAHOUTSUKAI_PLAYER_STORED_MANA:100,MAHOUTSUKAI_PLAYER_PROTECTIVE_DISPLACEMENT_USES:0,MAHOUTSUKAI_CANCEL_TIME:0L,MAHOUTSUKAI_PLAYER_DEATH_COLLECTION_USES_LEFT:0.0f},"mekanism:radiation":{radiation:1.0E-7d},"twilightforest:cap_shield":{permshields:0,tempshields:0},"citadel:extended_entity_data_citadel":{"Ice And Fire - Chicken Property Tracker":{TimeUntilNextEgg:1},"Ice And Fire - Siren Property Tracker":{CharmedBySiren:0b,SirenID:0},"Ice And Fire - Frozen Property Tracker":{TicksUntilUnfrozen:0,IsFrozen:0b},"Ice and Fire - Player Property Tracker":{DismountedDragon:0b,GauntletDamage:0,DreadPortalZ:0,DreadPortalY:0,DreadPortalX:0},"Ice And Fire - Chain Property Tracker":{ConnectedEntities:[]}},"pneumaticcraft:hacking":{},"shrink:shrunk":{width:0.49f,isshrinking:0b,defaulteyeheight:0.41650003f,fixed:0b,isshrunk:0b,height:0.49f},"eidolon:knowledge":{signs:[],facts:[]}},HandDropChances:[1.0f,1.0f],PersistenceRequired:0b,Items:[{Slot:3b,id:"rats:rat_upgrade_chicken_mount",Count:1b}],id:"rats:rat",UUID:[I;-1851283548,-2105456565,-1216062384,1639795720],RadiusPosZ:0,ColorVariant:3,Air:300s,DyeColor:0b,RadiusPosY:0,HandItems:[{},{}],RadiusPosX:0,ArmorDropChances:[1.0f,1.0f,1.0f,1.0f],CustomSearchZone:0b,Dyed:0b,Pos:[-1173.1232611003554d,67.69999998807907d,-16.27740983054919d],WildTrust:100,CanPickUpLoot:0b,HurtTime:0s,TransportingFluid:{FluidName:"minecraft:empty",Amount:0},CoinCooldown:0,ForgeData:{"naturesaura:time_alive":5320840},Sitting:0b,FallFlying:0b,ForcedAge:0,SearchRadius:16,PortalCooldown:0,MonsterOwnerUUID:"",DeathTime:0s,BoundingBox:[-1173.4216312046385d,67.69999998807907d,-16.606977166095206d,-1172.9316311951018d,68.18999999761581d,-16.116977156558463d],MountCooldown:0,EatenItems:0,DigCooldown:0,VisualFlag:0b,Age:0,TamedByMonster:0b,Motion:[0.0d,-0.0784000015258789d,0.0d],HomeDistance:-1.0f,Health:8.0f,LeftHanded:0b,OnGround:0b,Rotation:[147.74664f,-27.990467f],Plague:0b,Command:1,Fire:-1s,ArmorItems:[{},{},{},{}],HomePosZ:0,HomePosY:0,Dancing:0b,CookingProgress:0,IsMale:1b,HomePosX:0,RespawnCountdown:0,BreedCooldown:0}],Pos:[-1173.1232611003554d,67.0d,-16.27740983054919d],Fire:-1s,ArmorItems:[{},{},{},{}],CanPickUpLoot:0b,HurtTime:0s}
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}

-- Affected level --
Details:
	All players: 5 total; [ServerPlayerEntity['Renagade_Legend'/1078, l='ServerLevel[world]', x=-2793.82, y=55.67, z=429.66], ServerPlayerEntity['Eothorn'/39217, l='ServerLevel[world]', x=-1174.88, y=67.00, z=-16.52], ServerPlayerEntity['MbImAJosh'/767, l='ServerLevel[world]', x=-1030.83, y=97.97, z=-50.56], ServerPlayerEntity['Skystrike12'/51068, l='ServerLevel[world]', x=-1027.45, y=84.59, z=-53.01], ServerPlayerEntity['Zoe_Alex123'/49663, l='ServerLevel[world]', x=-1172.84, y=68.94, z=-20.94]]
	Chunk stats: ServerChunkCache: 6836
	Level dimension: minecraft:overworld
	Level spawn location: World: (-128,71,-224), Chunk: (at 0,4,0 in -8,-14; contains blocks -128,0,-224 to -113,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 14842725 game time, 18326532 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 93207 (now: false), thunder time: 49425 (now: false)
	Known server brands: vanilla, forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}

**Comment by GizmoTheMoonPig** [comment]
you removed the important part of the crashlog, which is then entire part before that part. The removed bit will actually tell me whats wrong, this just gives me info about the possible entity at fault
