### ISSUE TITLE
(7.2.0-1.16.5) Loading rat attractor when in debug world crashes game

### ISSUE THREAD

**Issue by Branjoman** [Alex-the-666/Rats#726]
When in a debug world (shift left click while cycling through worldgen types), going close enough to the rat attractor causes the game to instantly crash to desktop. The crash log is mostly the same repeating error messages, pointing to the one of the rat attractor instances as the issue.

Crash log snippets:
Description: Exception while updating neighbours

java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.invoke.MethodHandleNatives.linkCallSite(Unknown Source) ~[?:1.8.0_301] {}
	at net.minecraft.world.World.func_190524_a(World.java:343) ~[?:?]{re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World.func_195593_d(World.java:297) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at com.github.alexthe666.rats.server.blocks.BlockRatAttractor.updateState(BlockRatAttractor.java:81) ~[rats:7.2.0] {re:classloading}

-- Block being updated --
Details:
	Source block type: ID #rats:rat_attractor (block.rats.rat_attractor // com.github.alexthe666.rats.server.blocks.BlockRatAttractor)
	Block: Block{rats:rat_attractor}[powered=true,up=true]
	Block location: World: (351,70,7), Chunk: (at 15,4,7 in 21,0; contains blocks 336,0,0 to 351,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)

**Comment by GizmoTheMoonPig** [comment]
yeah I noticed this too. Fixed it in upcoming 1.19 version
