### ISSUE TITLE
Can't create new world on modpacks

### ISSUE THREAD

**Issue by SheReyy** [Alex-the-666/Rats#748]
Mc version: 1.16.5
Forge Version: 36.2.4
Java Version: 1.8.0.311

Hi! I'm working on an expert questing modpack for 1.16.5 with [this](https://pastebin.com/N09BxduF) modlist. When I try to create a world, I receive this crash:

```[09:35:55] [Worker-Main29/INFO]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]: ---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 11/28/21 9:35 AM
Description: Exception generating new chunk

java.lang.ClassCastException: net.minecraft.world.gen.WorldGenRegion cannot be cast to net.minecraft.world.server.ServerWorld
	at com.github.alexthe666.rats.server.entity.EntityRat.canEntityTypeSpawn(EntityRat.java:258) ~[?:7.2.0] {re:classloading}
	at com.github.alexthe666.rats.server.entity.RatsEntityRegistry$$Lambda$8976/1325254539.test(Unknown Source) ~[?:?] {}
	at net.minecraft.entity.EntitySpawnPlacementRegistry.func_223515_a(EntitySpawnPlacementRegistry.java:60) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:351) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:blame.mixins.json:WorldEntitySpawnerMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinWorldEntitySpawner,pl:mixin:A}
	at net.minecraft.world.gen.NoiseChunkGenerator.func_230354_a_(NoiseChunkGenerator.java:623) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:NoiseChunkGeneratorMixin,pl:mixin:APP:repurposed_structures.mixins.json:structures.StructureMobSpawningMixin,pl:mixin:APP:roadrunner.mixins.json:gen.cached_generator_settings.NoiseChunkGeneratorMixin,pl:mixin:APP:roadrunner.mixins.json:gen.fast_island_noise.NoiseChunkGeneratorMixin,pl:mixin:APP:roadrunner.mixins.json:gen.fast_noise_interpolation.NoiseChunkGeneratorMixin,pl:mixin:A}
	at net.minecraft.world.chunk.ChunkStatus.func_222602_b(ChunkStatus.java:89) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:common.world.ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$1856/1133823843.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:240) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:common.world.ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:world.chunk_ticking.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:roadrunner.mixins.json:world.player_chunk_tick.ThreadedAnvilChunkStorageMixin,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager$$Lambda$33554/922678848.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:world.chunk_ticking.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:roadrunner.mixins.json:world.player_chunk_tick.ThreadedAnvilChunkStorageMixin,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager$$Lambda$33539/629973894.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:roadrunner.mixins.json:world.chunk_task_system.ChunkTaskPrioritySystemMixin,pl:mixin:A}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$33552/2004335101.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:mixin,re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}```

**Comment by GizmoTheMoonPig** [comment]
see #771
