### ISSUE TITLE
Pied Piper/Apotheosis Spawner Crash

### ISSUE THREAD

**Issue by DocterDum** [Alex-the-666/Rats#771]
Heya,

I chucked a pied piper in an apotheosis spawner with the no AI upgrade it crashes the game (Breaking the world in the process). I have seen a similar issue before with twilight forest's swarm spiders - https://github.com/Shadows-of-Fire/Apotheosis/issues/648

Are you able to investigate?

I'm running a custom modpack, here's the relevant lines from the debug log:
`net.minecraft.crash.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]
Caused by: java.lang.ClassCastException: shadows.apotheosis.spawn.spawner.LyingLevel cannot be cast to net.minecraft.world.server.ServerWorld
	at com.github.alexthe666.rats.server.entity.EntityIllagerPiper.canSpawnOn(EntityIllagerPiper.java:227) ~[rats:7.2.0]
	at net.minecraft.entity.EntitySpawnPlacementRegistry.func_223515_a(EntitySpawnPlacementRegistry.java:60) ~[?:?]
	at shadows.apotheosis.spawn.spawner.ApothSpawnerTile$SpawnerLogicExt.checkSpawnRules(ApothSpawnerTile.java:272) ~[apotheosis:4.8.9A0]
	at shadows.apotheosis.spawn.spawner.ApothSpawnerTile$SpawnerLogicExt.func_98278_g(ApothSpawnerTile.java:199) ~[apotheosis:4.8.9A0]
	at net.minecraft.tileentity.MobSpawnerTileEntity.func_73660_a(SourceFile:62) ~[?:?]
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 5 more`

**Comment by GizmoTheMoonPig** [comment]
will be fixed in 1.19. This is indeed the same issue as the swarm spider one, and I went and made sure none of the other mobs also had this issue

**Comment by DocterDum** [comment]
FYI for future readers, if you experience this in 1.18 (Issue is only patched 1.19 and later), follow steps in https://github.com/Shadows-of-Fire/Apotheosis/issues/669

Open forge server config ( \serverconfig\forge-server.toml)
modify or add:
    removeErroringBlockEntities = false
    removeErroringEntities = false
