### ISSUE TITLE
A Crash bug and a "misstype?"

### ISSUE THREAD

**Issue by Levente423le** [Alex-the-666/Rats#876]
1. The crash happened when i opened a "Curdling Station" I have no idea why it happened.
(Rash Log below the "misstype")
2. theres a misstype (i think) is one of the rat updates lore.
![Képernyőkép 2024-06-01 180759](https://github.com/AlexModGuy/Rats/assets/80600451/6eae0d3f-6f9c-4a98-9f56-cadd6f245c23)
Crash log:
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-06-01 18:01:12
Description: Rendering screen

java.lang.OutOfMemoryError: Failed to resize buffer from 2145386496 bytes to -2147483648 bytes
	at com.mojang.blaze3d.platform.MemoryTracker.m_182529_(MemoryTracker.java:21) ~[client-1.20.1-20230612.114412-srg.jar%23234!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at com.mojang.blaze3d.vertex.BufferBuilder.m_85722_(BufferBuilder.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23234!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinBufferBuilder_SeparateAo,pl:mixin:APP:mixins.oculus.vertexformat.json:MixinBufferBuilder,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinBufferBuilder,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinBufferBuilder,pl:mixin:APP:embeddium.mixins.json:features.render.immediate.buffer_builder.BufferBuilderMixin,pl:mixin:APP:embeddium.mixins.json:core.render.immediate.consumer.BufferBuilderMixin,pl:mixin:APP:embeddium.mixins.json:features.render.immediate.buffer_builder.sorting.BufferBuilderMixin,pl:mixin:APP:embeddium.mixins.json:features.render.immediate.buffer_builder.intrinsics.BufferBuilderMixin,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinBufferBuilder_SegmentRendering,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.vertex.BufferBuilder.m_85665_(BufferBuilder.java:46) ~[client-1.20.1-20230612.114412-srg.jar%23234!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinBufferBuilder_SeparateAo,pl:mixin:APP:mixins.oculus.vertexformat.json:MixinBufferBuilder,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinBufferBuilder,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinBufferBuilder,pl:mixin:APP:embeddium.mixins.json:features.render.immediate.buffer_builder.BufferBuilderMixin,pl:mixin:APP:embeddium.mixins.json:core.render.immediate.consumer.BufferBuilderMixin,pl:mixin:APP:embeddium.mixins.json:features.render.immediate.buffer_builder.sorting.BufferBuilderMixin,pl:mixin:APP:embeddium.mixins.json:features.render.immediate.buffer_builder.intrinsics.BufferBuilderMixin,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinBufferBuilder_SegmentRendering,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.vertex.BufferBuilder.m_5752_(BufferBuilder.java:267) ~[client-1.20.1-20230612.114412-srg.jar%23234!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinBufferBuilder_SeparateAo,pl:mixin:APP:mixins.oculus.vertexformat.json:MixinBufferBuilder,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinBufferBuilder,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinBufferBuilder,pl:mixin:APP:embeddium.mixins.json:features.render.immediate.buffer_builder.BufferBuilderMixin,pl:mixin:APP:embeddium.mixins.json:core.render.immediate.consumer.BufferBuilderMixin,pl:mixin:APP:embeddium.mixins.json:features.render.immediate.buffer_builder.sorting.BufferBuilderMixin,pl:mixin:APP:embeddium.mixins.json:features.render.immediate.buffer_builder.intrinsics.BufferBuilderMixin,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinBufferBuilder_SegmentRendering,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.github.alexthe666.rats.client.gui.AutoCurdlerScreen.renderFluidStack(AutoCurdlerScreen.java:77) ~[Rats-1.20.1-8.1.2.jar%23226!/:1.20.1-8.1.2] {re:classloading}
	at com.github.alexthe666.rats.client.gui.AutoCurdlerScreen.m_7286_(AutoCurdlerScreen.java:103) ~[Rats-1.20.1-8.1.2.jar%23226!/:1.20.1-8.1.2] {re:classloading}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_88315_(AbstractContainerScreen.java:92) ~[client-1.20.1-20230612.114412-srg.jar%23234!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:shulkerboxtooltip-common.mixins.json:client.HandledScreenMixin,pl:mixin:APP:shulkerboxtooltip-forge.mixins.json:client.forge.HandledScreenMixin,pl:mixin:APP:adastra-common.mixins.json:client.AbstractContainerScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.github.alexthe666.rats.client.gui.AutoCurdlerScreen.m_88315_(AutoCurdlerScreen.java:87) ~[Rats-1.20.1-8.1.2.jar%23226!/:1.20.1-8.1.2] {re:classloading}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23234!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenMixin,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenAccessor,pl:mixin:APP:konkrete.mixin.json:IMixinScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427) ~[forge-1.20.1-47.2.17-universal.jar%23239!/:?] {re:mixin,re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) ~[forge-1.20.1-47.2.17-universal.jar%23239!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23234!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23234!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:xaerominimap:xaero_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23234!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:xaerominimap:xaero_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-1.20.1-47.2.17.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

**Comment by GizmoTheMoonPig** [comment]
Fixed the description thing (whoops!) but I dont think the crash here is my fault. I'll ask some people who are more knowledgeable on what mod may be messing with it and let you know

**Comment by GizmoTheMoonPig** [comment]
Got a couple people to look at it and they agreed its not the fault of this mod. One person said it may be ImmediatelyFast messing with the buffer, so I would try reporting it to them
